name: CI
on: [push, pull_request]

jobs:
  # linux-build:
  #   runs-on: ubuntu-latest
  #   env:
  #     PLATFORM: linux64
  #   steps:
  #     - uses: actions/checkout@master
  #       with:
  #         submodules: recursive

  #     @import build-linux.yml

  mac-build:
    runs-on: macos-latest
    env:
      PLATFORM: mac
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive

      @import install-neko.yml

      @import build-mac.yml

  linux-test:
    if: false
    # needs: linux-build
    runs-on: ubuntu-latest
    env:
      PLATFORM: linux64
      TEST: ${{matrix.target}}
      HXCPP_COMPILE_CACHE: ~/hxcache
    strategy:
      fail-fast: false
      matrix:
        target: [macro, js, hl, cpp, 'java,jvm', cs, php, python, lua, flash9, neko]
        include:
          - target: js
            # SAUCE: 1
            # SAUCE_TUNNEL_ID: 'linux-test'
            # SAUCE_BUILD: '${{env.GITHUB_RUN_NUMBER}}' # $(Build.BuildNumber)
          - target: hl
            APT_PACKAGES: cmake ninja-build
          - target: cpp
            APT_PACKAGES: gcc-multilib g++-multilib
          - target: lua
            APT_PACKAGES: ncurses-dev
          - target: flash9
            APT_PACKAGES: libglib2.0 libfreetype6 xvfb
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      # - uses: actions/download-artifact@v1
      #   with:
      #     name: linuxBinaries

      @import install-neko.yml

      @import test-linux.yml

  mac-test:
    # needs: mac-build
    runs-on: macos-latest
    env:
      PLATFORM: mac
      TEST: ${{matrix.target}}
      HXCPP_COMPILE_CACHE: ~/hxcache
    strategy:
      fail-fast: false
      matrix:
        target: [macro, js, hl, cpp, 'java,jvm', cs, php, python, lua, flash9, neko]
        include:
          - target: hl
            BREW_PACKAGES: ninja
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
      # - uses: actions/download-artifact@v1
      #   with:
      #     name: macBinaries

      @import install-neko.yml

      @import test-mac.yml


