jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        set -ex
        sudo add-apt-repository ppa:avsm/ppa -y # provides OPAM 2
        sudo add-apt-repository ppa:haxe/ocaml -y # provides newer version of mbedtls
        sudo apt-get update -qqy
        sudo apt-get install -qqy ocaml-nox camlp5 opam libpcre3-dev zlib1g-dev libgtk2.0-dev libmbedtls-dev ninja-build

    - name: Install Neko action
      uses: ./.github/actions/install-neko
      with:
        platform: linux64 # can be linux64, mac, windows, or windows64

    - name: Install OCaml libraries
      run: |
        set -ex
        opam init
        opam update
        opam pin add haxe . --no-action
        opam install haxe --deps-only
        opam list
        ocamlopt -v

    - name: Build Haxe
      run: |
        set -ex
        opam config exec -- make -s -j`nproc` STATICLINK=1 haxe
        opam config exec -- make -s haxelib
        make -s package_bin
        ls -l out
        ldd -v ./haxe
        ldd -v ./haxelib

    - name: Build xmldoc
      run: # TODO Build xmldoc

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: linuxBinaries
        path: out
